jahresrueckblick/settings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from webpage.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    # include webpage urls
    path('', index),
]   + static('media/', document_root='mediafiles/')

jahresrueckblick/webpage/models.py
from django.db import models

from .tools import cropImage

# Create a year model
class YearSlide(models.Model):

    class Meta:
        verbose_name = "Jahresrückblick (Jahr)"
        verbose_name_plural = "Jahresrückblicke (Jahre)"

    year = models.IntegerField(verbose_name="Jahreszahl", help_text="Bitte gib das Jahr an, für das du diesen Slide erstellen möchtest. Nach diesem Wert wird sortiert.")
    title = models.CharField(verbose_name="Titel", max_length=800, blank=True, help_text="Du kannst einen abweichenden Titel für die Slide angeben. Ist dieses Feld leer, wird das Jahr angezeigt.")
    slogan = models.TextField(blank=True, verbose_name="Motto", help_text="Du kannst ein Motto oder ein Thema für das Jahr angeben. Ist dieses Feld leer, wird nichts angezeigt.")
    document = models.FileField(blank=True, null=True, verbose_name="Jahresrückblick (PDF)", help_text="Du kannst eine PDF-Datei hochladen, die zu diesem Jahr gehört. Ist dieses Feld leer, wird nichts angezeigt.")
    document_image = models.ImageField(blank=True, null=True, verbose_name="Jahresrückblick (Titelbild)", help_text="Du kannst ein Vorschaubild hochladen, das zu diesem Dokument gehört. Ist dieses Feld leer, wird nichts angezeigt.")

    def name(self):
        if self.title:
            return self.title
        else:
            return self.year

    def __str__(self):
        return str(self.name()) + " - " + str(self.slogan)
    
# Create a Highlight model
class Highlight(models.Model):

    class Meta:
        verbose_name = "Highlight"

    year = models.ForeignKey(YearSlide, on_delete=models.CASCADE, verbose_name="Jahresrückblick / Jahr")
    title = models.CharField(max_length=800, verbose_name="Titel", help_text="Bitte gib einen Titel für das Bild an.")
    image = models.ImageField(verbose_name="Foto / Bild", help_text="Bitte lade ein Bild hoch. Bevorzugt einzelen Bilder mit einem Motiv im Mittelpunkt.")
    description = models.TextField(verbose_name="Beschreibung / Text", help_text="Bitte gib eine Beschreibung für das Event an.")
    date = models.DateField(verbose_name="Veranstaltungsdatum", help_text="Bitte gib das Datum für das Event an.")
    location = models.CharField(max_length=800, verbose_name="Veranstaltungsort", help_text="Bitte gib den Ort für das Event an.")
    
    def __str__(self):
        return self.title + " - " + str(self.year.year)

    @property
    def cropped_image(self):
        return cropImage(self.image)



# Create an Image model
class Image(models.Model):

    class Meta:
        verbose_name = "Einzelbild"
        verbose_name_plural = "Einzelbilder"

    year = models.ForeignKey(YearSlide, on_delete=models.CASCADE, verbose_name="Jahresrückblick / Jahr")
    image = models.ImageField(verbose_name="Foto / Bild", help_text="Bitte lade ein Bild hoch.")
    description = models.TextField(verbose_name="Beschreibung / Titel", help_text="Bitte gib eine Beschreibung an - zum Beispiel Anlass, Datum, Ort,...")
    
    @property
    def cropped_image(self):
        return cropImage(self.image)

    def __str__(self):
        return self.description + " - " + str(self.year.year)
    
# Create a position model combining year and person
class Position(models.Model):

    class Meta:
        verbose_name = "Person / Rolle"
        verbose_name_plural = "Personen / Rollen"

    year = models.ForeignKey(YearSlide, on_delete=models.CASCADE, verbose_name="Jahresrückblick / Jahr")
    person = models.CharField(verbose_name="Name der Person", max_length=800, help_text="Bitte gib den Namen der Person an.")
    position = models.CharField(verbose_name="Position", max_length=800, help_text="Bitte gib die Position an, die die Person im Jahr innehatte.")
    chairman = models.BooleanField(verbose_name="Ist Vorsitzender?", default=False, help_text="Bitte gib an, ob die Person Vorsitzender war.")

    def __str__(self):
        return self.person + " - " + self.position + " - " + str(self.year.year)
    
# Create a hounour model
class Honour(models.Model):

    class Meta:
        verbose_name = "Ehrung"
        verbose_name_plural = "Ehrungen"

    year = models.ForeignKey(YearSlide, on_delete=models.CASCADE, verbose_name="Jahresrückblick / Jahr")
    person = models.CharField(verbose_name="Name der Person", max_length=800, help_text="Bitte gib den Namen der Person an.")
    honour = models.CharField(verbose_name="Name der Ehrung", max_length=800, help_text="Bitte gib die Auszeichnung an, die die Person im Jahr erhalten hat.")
    
    def __str__(self):
        return self.person + " - " + self.honour + " - " + str(self.year.year)

jahresrueckblick/webpage/views.py
from django.shortcuts import render
from .models import *

# render index file
def index(request):
    # Get all year slides
    years = YearSlide.objects.all().order_by('-year')
    return render(request, 'index.html', {'years': years})

jahresrueckblick/webpage/templates/highlight.html
<div class="row {% if small %}m-3{% else %}m-2{% endif %} bordered">
    <div class="col-7 col-lg-5 col-xl-4 col-xxl-4" style="padding-left: 0px !important;">
        <a href="{{ highlight.image.url }}" data-lightbox="image-{{ highlight.date|date:"Y-m-y" }}" data-title="{{ highlight.title }}">
            <div style="background-image: url({{ highlight.cropped_image }});" class="image"></div>
        </a>
    </div>
    <div class="col-5 col-lg-7 col-xl-8 col-xxl-8">
        <h3 class="my-2 my-lg-3">{{ highlight.title }}</h3>
        <div class="p-1">
            <div class="row">
                <div class="col-6">
                    <i class="far fa-calendar"></i> {{ highlight.date|date:"d F Y" }} 
                </div>
                <div class="col-6">
                    <i class="fa fa-map-location-dot"></i> {{ highlight.location }}<br>
                </div>
            </div>
        </div>
        <p class="short d-none">{{ highlight.description|safe|truncatechars:300 }} {% if highlight.description|length > 300 %}- <a onclick="showMore(this)"><strong>Mehr lesen &raquo;</strong></a>{% endif %}</p>
        <p class="long">{{ highlight.description|safe }}</p>
    </div>
</div>

jahresrueckblick/webpage/templates/index.html
{% load math %}
{% load filter %}
<!DOCTYPE html>
<html lang="de">
    <head>
        <link rel="stylesheet" type="text/css" href="/static/css/main.css" />
        <link rel="stylesheet" type="text/css" href="/static/plugins/fullpage/fullpage.css" />
        <link rel="stylesheet" type="text/css" href="/static/plugins/bootstrap/css/bootstrap-grid.min.css" />
        <link rel="stylesheet" type="text/css" href="/static/plugins/lightbox2/css/lightbox.min.css" />
        <script type="text/javascript" src="/static/plugins/fontawesome/js/all.min.js"></script>
        <script type="text/javascript" src="/static/plugins/fullpage/fullpage.js"></script>
        <script type="text/javascript" src="/static/plugins/jquery/jquery-3.6.3.min.js"></script>
        <script type="text/javascript" src="/static/plugins/lightbox2/js/lightbox.min.js"></script>
        <script>
            const anchors = ['start',{% for year in years %}'{{ year.year }}'{% if not forloop.last %},{% endif %}{% endfor %},'ende'];
            const slides = ['Start',{% for year in years %}'{{ year.name }}'{% if not forloop.last %},{% endif %}{% endfor %},'Ende'];
        </script>
        <script type="text/javascript" src="/static/js/main.js"></script>
    </head>
    <body>
        <div id="fullpage">
            <section class="section odd">
                <div class="p-5">
                    <div class="row">
                        <div class="col-lg-3 col-md-5">
                            <img src="/static/img/logo.svg" width="100%" alt="Wirtschaftsjunioren Freiburg" class="mb-5" />
                        </div>
                        <div class="col-lg-9 col-md-7" style="text-align: right;">
                            <small>Mit freundlicher Unterstützung der <a href="https://software-design.de">SD Software-Design GmbH</a></small>
                        </div>
                        <div class="col-md-12">
                            <h1 class="mt-3 pt-3 pb-0 mb-0">{{ years.0.year|subtract:years.last.year }} Jahre</h1>
                            <h2 class="mt-0">Wirtschaftsjunioren Freiburg</h2>
                            <a href="#{{ years.0.year }}" style="text-decoration: none;">
                                <h3 class="action"><i class="fa fa-angles-down fa-beat fade-scale"></i> Scrollen, um den interaktiven Rückblick zu entdecken</h3></a>
                        </div>
                    </div>
                </div>
                <img id="skyline" src="/static/img/skyline1_blue.svg" width="100%;">
            </section>
            {% for year in years %}
            <section class="section fp-auto-height-responsive {% if forloop.counter0|divisibleby:2 %}even{% else %}odd{% endif %}">
                <div class="p-5">
                    <h1>{{ year.name }}</h1>
                    <div class="slide" data-anchor="slide1">
                        <div class="row">
                            <div class="col-12 col-lg-5 col-xl-3 positions">
                                <div class="row">
                                    <div class="col-6 col-lg-12">
                                        {% if year.position_set|getChairmen|length > 0 %}
                                            <h3><i class="fa fa-crown"></i> Vorstandsvorsitzende(r)</h3>
                                            <div class="ps-5">
                                                {% for position in year.position_set|getChairmen %}
                                                    {% if position.chairman %}
                                                        <strong>{{ position.person }}</strong><br>
                                                        <small>{{ position.position }}<br></small>
                                                    {% endif %}
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                        {% if year.position_set|getNonChairmen|length > 0 %}
                                        <h3><i class="fa fa-users"></i> Vorstandsteam</h3>
                                        <div class="ps-5">
                                            {% for position in year.position_set|getNonChairmen %}
                                                {% if not position.chairman %}
                                                    <strong>{{ position.person }}</strong><br>
                                                    <small>{{ position.position }}<br></small>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        {% endif %}
                                    </div>
                                    <div class="col-6 col-lg-12">
                                        {% if year.honour_set.all|length > 0 %}
                                        <h3><i class="fa fa-medal"></i> Ehrungen</h3>
                                        <div class="ps-5">
                                            {% for honour in year.honour_set.all %}
                                                <strong>{{ honour.person }}</strong><br>
                                                <small>{{ honour.honour }}<br></small>
                                            {% endfor %}
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% if year.document and year.document_image %}
                                <div class="col-12 col-lg-3">
                                    <div class="row">
                                        <div class="col-12">
                                            <h2 class="mt-3 mt-lg-0">Download</h2>
                                        </div>
                                        <div class="col-12 col-sm-6 col-lg-12">
                                            {% if year.document and year.document_image %}
                                            <img src="{{ year.document_image.url }}" class="pdf-preview">
                                            <br><br>
                                        </div>
                                        <div class="col-12 col-sm-6 col-lg-12">
                                            <a href="{{ year.document.url }}">
                                                <div class="pdf-label">
                                                    <i class="fa fa-file-pdf"></i>  Jahresrückblick als PDF &raquo;
                                                </div>
                                            </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-lg-12 col-xl-6 d-none d-lg-block">
                            {% else %}
                            <div class="col-12 col-lg-7 col-xl-9 d-none d-lg-block">
                            {% endif %}
                                {% if not year.document and year.highlight_set.count == 0 %}
                                    <h3>Leider fehlen uns für {{ year.name }} noch Bilder und Aufzeichnungen!</h3>
                                    Wenn du Bilder, Texte oder Unterlagen aus dem Jahr {{ year.name }} hast, sende sie uns bitte an "<em>presse@wj-freiburg.de</em>"!
                                {% else %}
                                    <h2 class="mt-3 mt-lg-0">{% if year.slogan %}{{ year.slogan }}{% else %}Highlights{% endif %}</h2>
                                {% endif %}
                                {% for highlight in year.highlight_set.all|limit:3 %}
                                {% include 'highlight.html' with small=True %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="slide d-lg-none" data-anchor="slide4">
                        <h2 class="mt-0 mb-4">Unsere Highlights</h2>
                        <div class="row">
                            <div class="col-12">
                                Im Jahr {{ year.name }} haben wir folgende besondere Highlights in unserem Kreis organisiert. Swipe nach rechs, um weitere Termine und Events zu sehen.<br><br>
                            </div>
                            {% for highlight in year.highlight_set.all|limit:3 %}
                            <div class="col-12 col-lg-6">
                                {% include 'highlight.html' %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% if year.image_set.count > 0 %}
                    <div class="slide" data-anchor="slide3">
                        <h2 class="mt-0 mb-4">Bilder und Impressionen</h2>
                        <div class="row">
                            {% for image in year.image_set.all|startat:0|limit:24 %}
                            <div class="col-12 col-md-6 col-lg-2 p-1 text-center">
                                <a href="{{ image.image.url }}" data-lightbox="image-{{ image.pk }}" data-title="{{ image.description }}">
                                    <img class="image" src="{{ image.cropped_image }}" width="100%" loading="lazy">
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    {% if year.image_set.count > 24 %}
                    <div class="slide" data-anchor="slide5">
                        <h2 class="mt-0 mb-4">Bilder und Impressionen</h2>
                        <div class="row">
                            {% for image in year.image_set.all|startat:24|limit:48 %}
                            <div class="col-12 col-md-6 col-lg-2 p-1 text-center">
                                <a href="{{ image.image.url }}" data-lightbox="image-{{ image.pk }}" data-title="{{ image.description }}">
                                    <img class="image" src="{{ image.cropped_image }}" width="100%" loading="lazy">
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    {% if year.highlight_set.count > 3 %}
                    <div class="slide" data-anchor="slide2">
                        <h2 class="mt-0 mb-4">Weitere Termine & Events</h2>
                        <div class="row">
                            {% for highlight in year.highlight_set.all|startat:3|limit:6 %}
                            <div class="col-12 col-lg-6">
                                {% include 'highlight.html' %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    {% if year.highlight_set.count > 9 %}
                    <div class="slide" data-anchor="slide3">
                        <h2 class="mt-0 mb-4">Weitere Termine & Events</h2>
                        <div class="row">
                            {% for highlight in year.highlight_set.all|startat:9 %}
                            <div class="col-12 col-lg-6">
                                {% include 'highlight.html' %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </section>
            {% endfor %}

            <section class="section odd">
                <div class="p-5">
                    <div class="row">
                        <div class="col-md-6">
                            <img src="/static/img/logo.svg" width="400" alt="Wirtschaftsjunioren Freiburg" class="mb-5" />
                        </div>
                        <div class="col-md-6" style="text-align: right;">
                        </div>
                        <div class="col-md-12">
                            <h2 class="mt-5">Der digitale Jahresrückblick...</h2>
                            <h3 style="color: lightgrey; font-size: 2em;">...mit freundlicher Unterstützung der SD Software-Design GmbH</h3>
                            <br>
                            <img src="/static/img/sd.png" width="600" alt="SD Software-Design GmbH" class="mb-5" />
                        </div>
                    </div>
                </div>
                <img id="skyline" src="/static/img/skyline1_blue.svg" width="100%;">
            </section>
        </div>
    </body>
</html>